language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script:
  - pytest
  - coverage run tests.py
after_success:
  - codecov
